project_name: mqtt-alerting
version: 2

before:
  hooks:
    - go mod tidy
    - sh -c "cd web && npm install -g pnpm@11.5.1 && pnpm install --frozen-lockfile && pnpm run build"

builds:
  - id: mqtt-alerting
    main: ./main.go
    binary: mqtt-alerting
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mqtt-home/mqtt-alerting/version.Version={{.Version}} -X github.com/mqtt-home/mqtt-alerting/version.GitCommit={{.Commit}} -X github.com/mqtt-home/mqtt-alerting/version.BuildTime={{.Date}}

dockers:
  - image_templates:
      - "pharndt/mqtt-alerting:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - web/dist/
    skip_push: false

  - image_templates:
      - "pharndt/mqtt-alerting:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
    extra_files:
      - web/dist/
    skip_push: false

docker_manifests:
  - id: tag
    name_template: "pharndt/mqtt-alerting:{{ .Tag }}"
    image_templates:
      - pharndt/mqtt-alerting:{{ .Tag }}-amd64
      - pharndt/mqtt-alerting:{{ .Tag }}-arm64

  - id: latest
    name_template: "pharndt/mqtt-alerting:latest"
    image_templates:
      - pharndt/mqtt-alerting:{{ .Tag }}-amd64
      - pharndt/mqtt-alerting:{{ .Tag }}-arm64

release:
  disable: false
  mode: replace
  draft: false
  prerelease: auto
  make_latest: true
  skip_upload: true
